spring:
  datasource:
    url: jdbc:postgresql://ec2-54-228-218-84.eu-west-1.compute.amazonaws.com:5432/d8j28ol9gk5cpe
    username: robxuhfnbmuqse
    password: 89e904f2f508a37ce25a568ef6fbb7c8a07ddfff6cf98e62d88af413f24e2acc
  flyway:
    url: jdbc:postgresql://ec2-54-228-218-84.eu-west-1.compute.amazonaws.com:5432/d8j28ol9gk5cpe
    schemas: storedb
    user: robxuhfnbmuqse
    password: 89e904f2f508a37ce25a568ef6fbb7c8a07ddfff6cf98e62d88af413f24e2acc
  jpa:
    show-sql: false