spring:
  datasource:
    url: jdbc:postgresql://34.118.118.79:5432/postgres
    username: postgres
    password: postgres
  jpa:
    show-sql: false
  cloud:
    gcp:
      sql:
        instance-connection-name: alert-synapse-371215:europe-central2:alert-synapse-371215-db
        database-name: postgres
