spring:
  datasource:
    url: jdbc:postgresql://34.116.203.11:5432/postgres
    username: postgres
    password: H|7Qp]:=f6VUq]]%
  flyway:
    url: jdbc:postgresql://34.116.203.11:5432/postgres
    user: postgres
    password: H|7Qp]:=f6VUq]]%
    schemas: storedb
  jpa:
    show-sql: false